### ISSUE TITLE
Member 상태 추가

### ISSUE THREAD

**Issue by junhaesung** [depromeet/ygtang-server#196]
## Feature Description
- 데이터가 삭제되면 지표 수집할수 없어서, 삭제상태로 변경함 
- 탈퇴시 member 데이터 soft delete 방식으로 변경

## Todo list
- [ ] status column 추가
- [ ] 회원 탈퇴 로직 수정 (delete - update)
- [ ] 회원 조회 로직 수정 (status 조건 추가)
