### ISSUE TITLE
자동 재시작 스크립트 개선

### ISSUE THREAD

**Issue by junhaesung** [depromeet/ygtang-server#198]
## Feature Description
- 개발서버에 적용된 자동 재시작 스크립트 개선

## Todo list
- [ ] 배포시점에 의도적으로 컨테이너 종료시키는 경우는 재시작시키지않음
- [ ] 스크립트에의해 재시작하는 경우, 슬랙 메시지 발송
- [ ] OOM 으로 종료되는 경우 heap dump 남기는 옵션 추가
- [ ] xmx 옵션 추가 (512MB 정도)
